version: 2
updates:
  # Enable version updates for npm in each subproject
  - package-ecosystem: "npm"
    directory: "/js-wdio-web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ts-wdio-web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/js-playwright"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ts-playwright"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/js-cypress"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/ts-cypress"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/react-unit-tester"
    schedule:
      interval: "weekly"

  # Enable updates for GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
