name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language-folder:
          - { language: "javascript", folder: "js-wdio-web" }
          - { language: "typescript", folder: "ts-wdio-web" }

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the environment based on the language
      - name: Set up environment for ${{ matrix.language-folder.language }}
        run: |
          if [ "${{ matrix.language-folder.language }}" == "javascript" ] || [ "${{ matrix.language-folder.language }}" == "typescript" ]; then
            echo "Setting up Node.js environment"
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi

      # Inject .npmrc with the secret
      - name: Configure .npmrc
        run: |
          echo "${{ secrets.EVINCED_NPM_TOKEN }}" > ~/.npmrc

      # Install dependencies
      - name: Install dependencies
        run: |
          cd ${{ matrix.language-folder.folder }}
          npm install

      # Run tests
      - name: Run tests
        run: |
          cd ${{ matrix.language-folder.folder }}
          npm test
