name: Evinced Examples CI/CD tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language-folder:
          - { language: "javascript", folder: "js-wdio-web" }
          - { language: "typescript", folder: "ts-wdio-web" }

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the environment based on the language, this is to handle additional languages, configure later for Java tests
      - name: Set up environment for ${{ matrix.language-folder.language }}
        run: |
          if [ "${{ matrix.language-folder.language }}" == "javascript" ] || [ "${{ matrix.language-folder.language }}" == "typescript" ]; then
            echo "Setting up Node.js environment"
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi

      # Install Chrome and dependencies
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            google-chrome-stable \
            chromedriver \
            fonts-liberation \
            libappindicator3-1 \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils

      - name: Add ChromeDriver to PATH
        run: sudo ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver

      # Inject .npmrc with the secret from GitHub secrets
      - name: Configure .npmrc
        run: |
          echo "${{ secrets.EVINCED_NPM_TOKEN }}" > ~/.npmrc

      # Install dependencies for the test
      - name: Install dependencies
        run: |
          cd ${{ matrix.language-folder.folder }}
          npm install

      # Run tests
      - name: Run tests
        run: |
          cd ${{ matrix.language-folder.folder }}
          if [ -f "wdio.conf.js" ]; then
            echo "Running WebDriverIO tests"
            npm run wdio
          else
            echo "Running standard tests"
            npm run test
          fi

      # Debugging Chrome and ChromeDriver versions (Optional)
      - name: Check Chrome version
        run: google-chrome --version

      - name: Check ChromeDriver version
        run: chromedriver --version
