name: Evinced Examples CI/CD tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

jobs:
  call-UT-workflow:
    uses: ./.github/workflows/unit-tester.yml

  call-JS-wdio:
    uses: ./.github/workflows/js-wdio.yml

  call-TS-wdio:
    uses: ./.github/workflows/ts-wdio.yml

  call-JS-cypress:
    uses: ./.github/workflows/js-cypress.yml

  call-JS-playwright:
    uses: ./.github/workflows/js-playwright.yml

  call-TS-playwright:
    uses: ./.github/workflows/ts-playwright.yml
