name: Evinced Examples CI/CD tests

on:
  push:
    # branches:
    #   - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

jobs:
  call-UT-workflow:
    uses: ./.github/workflows/unit-tester.yml

  call-JS-wdio:
    uses: ./.github/workflows/js-wdio.yml

  call-TS-wdio:
    uses: ./.github/workflows/ts-wdio.yml

  call-JS-cypress:
    uses: ./.github/workflows/js-cypress.yml
    secrets:
      EVINCED_NPM_TOKEN: ${{ secrets.EVINCED_NPM_TOKEN }}
      EVINCED_SERVICE_ID: ${{ secrets.EVINCED_SERVICE_ID }}
      EVINCED_API_KEY: ${{ secrets.EVINCED_API_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  call-JS-playwright:
    uses: ./.github/workflows/js-playwright.yml

  call-TS-playwright:
    uses: ./.github/workflows/ts-playwright.yml
