name: JavaScript Cypress Tests

on:
  workflow_call:
    secrets:
      EVINCED_NPM_TOKEN:
        required: true
      EVINCED_SERVICE_ID:
        required: true
      EVINCED_API_KEY:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  js-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: act10ns/slack@v2
        with:
          status: starting
          channel: "#workflows"
          message: "Starting JavaScript Cypress Tests"
        if: always()

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Debug token length
        run: |
          echo "Token length: ${#EVINCED_NPM_TOKEN}"
        env:
          EVINCED_NPM_TOKEN: ${{ secrets.EVINCED_NPM_TOKEN }}

      - name: Configure .npmrc
        env:
          EVINCED_NPM_TOKEN: ${{ secrets.EVINCED_NPM_TOKEN }}
        run: |
          echo "@evinced:registry=https://evinced.jfrog.io/artifactory/api/npm/restricted-npm-local/" > ~/.npmrc
          echo "//evinced.jfrog.io/artifactory/api/npm/restricted-npm-local/:_authToken=${{ secrets.EVINCED_NPM_TOKEN }}" >> ~/.npmrc

      - name: Debug .npmrc
        run: cat ~/.npmrc

      - name: Install dependencies
        run: |
          cd js-cypress
          npm install --userconfig=~/.npmrc

      - name: Run Cypress Tests
        id: run-js-cypress-tests
        env:
          EVINCED_SERVICE_ID: ${{ secrets.EVINCED_SERVICE_ID }}
          EVINCED_API_KEY: ${{ secrets.EVINCED_API_KEY }}
        run: |
          cd js-cypress
          npx cypress run

      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
